# goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - dir: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      # - windows
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
      - "ppc64le"
      - "s390x"
    goarm:
      - "6"
      - "7"

release:
  mode: keep-existing

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: dagu-org
      name: homebrew-brew
    directory: Formula
    homepage: "https://github.com/dagu-org/dagu"
    description: "A compact, portable, and language-agnostic workflow engine. It aims to solve greater problems for developers."
    license: "GNU General Public License v3.0"
    custom_block: |
      service do
        run [opt_bin/"dagu", "start-all"]
        keep_alive true
        error_log_path var/"log/dagu.log"
        log_path var/"log/dagu.log"
        working_dir var
      end

  # Deprecated brew tap:
  - repository:
      owner: yohamta
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/dagu-org/dagu"
    description: "A compact, portable, and language-agnostic workflow engine. It aims to solve greater problems for developers."
    license: "GNU General Public License v3.0"
    custom_block: |
      service do
        run [opt_bin/"dagu", "start-all"]
        keep_alive true
        error_log_path var/"log/dagu.log"
        log_path var/"log/dagu.log"
        working_dir var
      end

snapcrafts:
  - name: dagu
    title: Dagu
    publish: true
    summary: "A compact, portable, and language-agnostic workflow engine. It aims to solve greater problems for developers."
    description: |
      Dagu is a compact, portable workflow engine implemented in Go. It provides a declarative model for orchestrating command execution across diverse environments, including shell scripts, Python commands, containerized operations, or remote commands.
      Dagu’s design emphasizes minimal external dependencies: it operates solely as a single binary without requiring an external database. A browser-based graphical interface (UI) is provided for real-time monitoring, rendering the status and logs of workflows. This zero-dependency structure makes the system easy to install and well-suited to various infrastructures, including local or air-gapped systems. This local-first architecture also ensures that sensitive data or proprietary workflows remain secure.
    confinement: strict
    grade: stable
    base: core24
    license: "GPL-3.0"
    apps:
      dagu:
        command: dagu start-all
        daemon: simple
        plugs:
          - network
          - home
          - personal-files
        restart_condition: "always"
